// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogmpjhccijqbamukdker.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbXBqaGNjaWpxYmFtdWtka2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTA4NDAsImV4cCI6MjA2MDU2Njg0MH0.79L_kDn6x_lbX-ATJgtQlnMh7Idf7kL8AOKPvmJ2ky8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);