// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnzkkyhhqxrbyhslwply.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuemtreWhocXhyYnloc2x3cGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDM0MzAsImV4cCI6MjA2MDU3OTQzMH0.ft83JKYqqKtOeELYqAxT4IKs0utPdXRE5-c7v3ATuuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);